# AUTOGENERATED FROM 'src/queries/record/GetRecord.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import decimal
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetRecordResult(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    id_service: str | None
    active: bool | None
    status: str | None
    type: str | None
    value: decimal.Decimal | None
    details: str | None
    entity: list[GetRecordResultEntityItem]
    event: list[GetRecordResultEventItem]
    movement: list[GetRecordResultMovementItem]


@dataclasses.dataclass
class GetRecordResultEntityItem(NoPydanticValidation):
    id: uuid.UUID
    name: str | None


@dataclasses.dataclass
class GetRecordResultEventItem(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    type: str | None
    status: bool | None
    date: datetime.date | None


@dataclasses.dataclass
class GetRecordResultMovementItem(NoPydanticValidation):
    id: uuid.UUID
    type: str | None
    value: decimal.Decimal
    installment: int


async def GetRecord(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetRecordResult | None:
    return await executor.query_single(
        """\
        select Record {
            name,
            id_service,
            active,
            status,
            type,
            value,
            details,
            entity: {
                id,
                name,
            },
            event: {
                id,
                name,
                type,
                status,
                date
            },
            movement: {
                id,
                type,
                value,
                installment,
            }
        } filter .id = <uuid>$id\
        """,
        id=id,
    )
