# AUTOGENERATED FROM 'src/queries/record/UnlinkMovement.edgeql' WITH:
#     $ gel-py


from __future__ import annotations

import dataclasses
import uuid

import gel


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = list
        return []


@dataclasses.dataclass
class UnlinkMovementResult(NoPydanticValidation):
    id: uuid.UUID


async def UnlinkMovement(
    executor: gel.AsyncIOExecutor,
    *,
    movement_id: uuid.UUID,
    record: uuid.UUID,
) -> UnlinkMovementResult | None:
    return await executor.query_single(
        """\
        update Record filter .id = <uuid>$record set {
            movement -= (select Movement filter .id = <uuid>$movement_id)
        }\
        """,
        movement_id=movement_id,
        record=record,
    )
