# AUTOGENERATED FROM 'src/queries/record/UnlinkScheduler.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UnlinkSchedulerResult(NoPydanticValidation):
    id: uuid.UUID


async def UnlinkScheduler(
    executor: gel.AsyncIOExecutor,
    *,
    schedule_id: uuid.UUID,
    record: uuid.UUID,
) -> UnlinkSchedulerResult | None:
    return await executor.query_single(
        """\
        update Record filter .id = <uuid>$record set {
            event -= (select Scheduler filter .id = <uuid>$schedule_id)
        }\
        """,
        schedule_id=schedule_id,
        record=record,
    )
