# AUTOGENERATED FROM 'src/queries/record/UnlinkEntity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UnlinkEntityResult(NoPydanticValidation):
    id: uuid.UUID


async def UnlinkEntity(
    executor: gel.AsyncIOExecutor,
    *,
    entity_id: uuid.UUID,
    id_record: uuid.UUID,
) -> UnlinkEntityResult | None:
    return await executor.query_single(
        """\
        update Record filter .id = <uuid>$id_record set {
            entity-= (select Entity filter .id = <uuid>$entity_id)
        }\
        """,
        entity_id=entity_id,
        id_record=id_record,
    )
