# AUTOGENERATED FROM 'src/queries/schedule/GetSchedule.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetScheduleResult(NoPydanticValidation):
    id: uuid.UUID
    type_tag: str | None
    name: str | None
    status: bool | None
    date_beginning: datetime.datetime | None
    date_ending: datetime.datetime | None
    notes: str | None


async def GetSchedule(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetScheduleResult | None:
    return await executor.query_single(
        """\
        select Scheduler{
            type_tag,
            name,
            status,
            date_beginning,
            date_ending,
            notes,
        }filter .id = <uuid>$id\
        """,
        id=id,
    )
