# AUTOGENERATED FROM 'src/queries/schedule/UpdateSchdeule.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateSchdeuleResult(NoPydanticValidation):
    id: uuid.UUID


async def UpdateSchdeule(
    executor: gel.AsyncIOExecutor,
    *,
    name: str | None = None,
    type_tag: str | None = None,
    status: bool | None = None,
    date: datetime.date | None = None,
    beginning_time: datetime.time | None = None,
    ending_time: datetime.time | None = None,
    notes: str | None = None,
    id: uuid.UUID,
) -> UpdateSchdeuleResult | None:
    return await executor.query_single(
        """\
        update Scheduler filter .id = <uuid>$id set {
            name:= <optional str>$name ?? .name,
            type_tag:= <optional str>$type_tag ?? .type_tag,
            status:= <optional bool>$status ?? .status,
            date:= <optional cal::local_date>$date ?? .date,
            beginning_time:= <optional cal::local_time>$beginning_time ?? .beginning_time,
            ending_time:= <optional cal::local_time>$ending_time ?? .ending_time,
            notes:=<optional json>$notes ?? .notes,
        }\
        """,
        name=name,
        type_tag=type_tag,
        status=status,
        date=date,
        beginning_time=beginning_time,
        ending_time=ending_time,
        notes=notes,
        id=id,
    )
