# AUTOGENERATED FROM 'src/queries/user/CreateUser.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID


async def CreateUser(
    executor: gel.AsyncIOExecutor,
    *,
    identity_id: uuid.UUID,
    type_insert: str,
    name: str,
    refreshe_token: uuid.UUID,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        with identity := <ext::auth::Identity><uuid>$identity_id,
        emailFactor := (
            SELECT ext::auth::EmailFactor FILTER .identity = identity
        ),
        query_todo:= (
        insert Account {
            name := <str>$name,
            email:= emailFactor.email,
            refresh_token:= <uuid>$refreshe_token,
            identity := identity
        }
        ) if <str>$type_insert = "organization" else (
        insert Individual {
            name := <str>$name,
            email:= emailFactor.email,
            refresh_token:= <uuid>$refreshe_token,
            identity := identity
        }
        )
        select query_todo\
        """,
        identity_id=identity_id,
        type_insert=type_insert,
        name=name,
        refreshe_token=refreshe_token,
    )
