# AUTOGENERATED FROM 'src/queries/user/CreateBankAccount.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateBankAccountResult(NoPydanticValidation):
    id: uuid.UUID


async def CreateBankAccount(
    executor: gel.AsyncIOExecutor,
    *,
    bank_name: str,
    account_name: str,
    balance: str,
    category: str | None = None,
    ignore_on_totals: bool,
    type: str | None = None,
    notes: str | None = None,
) -> CreateBankAccountResult:
    return await executor.query_single(
        """\
        with add_bank:=(
            insert BankAccount {
                bank_name:= <str>$bank_name,
                account_name:= <str>$account_name,
                balance:= to_decimal(<str>$balance, 'FM999999999999.99'),
                category_tag:= <optional str>$category,
                ignore_on_totals:= <bool>$ignore_on_totals,
                type_tag:= <optional str>$type,
                notes:= <optional json>$notes,
            }
        ),
        select (add_bank){id};\
        """,
        bank_name=bank_name,
        account_name=account_name,
        balance=balance,
        category=category,
        ignore_on_totals=ignore_on_totals,
        type=type,
        notes=notes,
    )
