# AUTOGENERATED FROM 'src/queries/user/DeleteBankAccount.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteBankAccountResult(NoPydanticValidation):
    id: uuid.UUID


async def DeleteBankAccount(
    executor: gel.AsyncIOExecutor,
    *,
    account: uuid.UUID,
    user: uuid.UUID,
) -> DeleteBankAccountResult | None:
    return await executor.query_single(
        """\
        with account:= <uuid>$account,
        deleteAccount:= (
            delete BankAccount filter .id = account
        )
        update InternalUser filter .id = <uuid>$user set {
            account -= (select deleteAccount)
        }\
        """,
        account=account,
        user=user,
    )
