# AUTOGENERATED FROM 'src/queries/user/GetUserData.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserDataResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    email: str
    auth: bool
    total_balance: str
    settings: GetUserDataResultSettings | None
    movement: list[GetUserDataResultMovementItem]
    entity: list[GetUserDataResultEntityItem]
    payment_income: list[GetUserDataResultPaymentIncomeItem]
    payment_expense: list[GetUserDataResultPaymentIncomeItem]
    record: list[GetUserDataResultRecordItem]
    event: list[GetUserDataResultEventItem]
    account: list[GetUserDataResultAccountItem]


@dataclasses.dataclass
class GetUserDataResultAccountItem(NoPydanticValidation):
    id: uuid.UUID
    bank_name: str
    account_name: str
    balance_str: str | None


@dataclasses.dataclass
class GetUserDataResultEntityItem(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    email: str
    govt_id: str | None
    type_entity: str | None
    id_type: str | None
    status: bool | None
    address: list[GetUserDataResultEntityItemAddressItem]


@dataclasses.dataclass
class GetUserDataResultEntityItemAddressItem(NoPydanticValidation):
    id: uuid.UUID
    state: str | None
    city: str | None


@dataclasses.dataclass
class GetUserDataResultEventItem(NoPydanticValidation):
    id: uuid.UUID
    type_entry: str | None
    name: str | None
    status: bool | None
    date: datetime.date | None


@dataclasses.dataclass
class GetUserDataResultMovementItem(NoPydanticValidation):
    id: uuid.UUID
    type_movement: str | None
    value_str: str
    installment: int
    payment: list[GetUserDataResultMovementItemPaymentItem]


@dataclasses.dataclass
class GetUserDataResultMovementItemPaymentItem(NoPydanticValidation):
    id: uuid.UUID
    status: bool | None
    payment_date: datetime.date | None


@dataclasses.dataclass
class GetUserDataResultPaymentIncomeItem(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    type_payment: str | None
    value_str: str | None
    payment_date: datetime.date | None
    status: bool | None
    movement: GetUserDataResultPaymentIncomeItemMovement


@dataclasses.dataclass
class GetUserDataResultPaymentIncomeItemMovement(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetUserDataResultRecordItem(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    id_service: str | None
    active: bool | None
    status: str | None
    type_record: str | None


@dataclasses.dataclass
class GetUserDataResultSettings(NoPydanticValidation):
    id: uuid.UUID
    account_types: list[str] | None
    default_bank_account: GetUserDataResultSettingsDefaultBankAccount | None
    record_title: str | None
    movement_title: str | None
    entity_title: str | None
    entity_types: list[str] | None
    entity_id_types: list[str] | None
    contact_number_types: list[str] | None
    record_types: list[str] | None
    record_status: list[str] | None
    movement_income_types: list[str] | None
    movement_expense_types: list[str] | None
    scheduler_types: list[str] | None
    movement_cycle_types: list[str] | None


@dataclasses.dataclass
class GetUserDataResultSettingsDefaultBankAccount(NoPydanticValidation):
    id: uuid.UUID


async def GetUserData(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetUserDataResult | None:
    return await executor.query_single(
        """\
        with user_id:= (<uuid>$id),
        selected_user:= assert_single((select InternalUser filter .id = user_id)),
        select selected_user {
            name,
            email,
            auth:= true,
            total_balance:= to_str(sum((select selected_user.account.balance))),
            settings: {
                id,
                account_types,
                default_bank_account: {id},
                record_title,
                movement_title,
                entity_title,
                entity_types,
                entity_id_types,
                contact_number_types,
                record_types,
                record_status,
                movement_income_types,
                movement_expense_types,
                scheduler_types,
                movement_cycle_types
            },
            movement: {
                id,
                type_movement:= .type,
                value_str:= to_str(.value),
                installment,
                payment: {
                    id,
                    status,
                    payment_date,
                }
            },
            entity: {
                id,
                name,
                email,
                govt_id,
                type_entity:= .type,
                id_type,
                status,
                address: {
                    state,
                    city,
                },
            },
            payment_income:{
                id,
                name,
                type_payment:= .type,
                value_str:=to_str(.value),
                payment_date,
                status,
                movement:{id}
            },
            payment_expense:{
                id,
                name,
                type_payment:= .type,
                value_str:=to_str(.value),
                payment_date,
                status,
                movement:{id}
            },
            record: {
                id,
                name,
                id_service,
                active,
                status,
                type_record:= .type,
            },
            event:{
                id,
                type_entry:= .type,
                name,
                status,
                date,
            },
            account: {
                id,
                bank_name,
                account_name,
                balance_str:=to_str(.balance),
            },
        }\
        """,
        id=id,
    )
