# AUTOGENERATED FROM 'src/queries/movement/CreatePayment.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreatePaymentResult(NoPydanticValidation):
    id: uuid.UUID


async def CreatePayment(
    executor: gel.AsyncIOExecutor,
    *,
    is_due: datetime.date,
    name: str,
    status: bool,
    type_tag: str,
    value: str,
    ignore_in_totals: bool | None = None,
    category: str,
    payment_date: datetime.date | None = None,
    account: uuid.UUID,
    movement: uuid.UUID,
) -> CreatePaymentResult:
    return await executor.query_single(
        """\
        with isit:= <cal::local_date>$is_due,
        event_:=(insert Scheduler{
            name:=<str>$name,
            date_beginning:=cal::to_local_datetime(<str>isit),
            status:=<bool>$status,
        }),
        insert Payment {
            name:= <str>$name,
            type_tag:=<str>$type_tag,
            value:=to_decimal(<str>$value, 'FM999999999999D99'),
            ignore_in_totals:= <optional bool>$ignore_in_totals,
            category_tag:= <str>$category,
            payment_date:= <optional cal::local_date>$payment_date ?? isit,
            is_due:= isit,
            status:= <bool>$status,
            account:= assert_single((select BankAccount filter .id = <uuid>$account)),
            movement:= assert_single((select Movement filter .id = <uuid>$movement)),
            event:=event_,
        }\
        """,
        is_due=is_due,
        name=name,
        status=status,
        type_tag=type_tag,
        value=value,
        ignore_in_totals=ignore_in_totals,
        category=category,
        payment_date=payment_date,
        account=account,
        movement=movement,
    )
