# AUTOGENERATED FROM 'src/queries/entity/CreateContact.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateContactResult(NoPydanticValidation):
    contact: CreateContactResultContact | None
    updated: CreateContactResultUpdated | None


@dataclasses.dataclass
class CreateContactResultContact(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class CreateContactResultUpdated(NoPydanticValidation):
    id: uuid.UUID


async def CreateContact(
    executor: gel.AsyncIOExecutor,
    *,
    entity: uuid.UUID,
    type_tag: str,
    notes: str | None = None,
    number: str,
) -> CreateContactResult:
    return await executor.query_single(
        """\
        with entity:=assert_single((select Entity filter .id = <uuid>$entity)),
        add_contact:= (
            insert Contact{
                type_tag:= <str>$type_tag,
                complement:=<optional str>$notes,
                number:= <str>$number,
            }
        ) if exists entity else <Contact>{},
        update_entity:= (update entity set {
            phone += add_contact
        }),
        select {
            contact := add_contact { id },
            updated := update_entity { id }
        }\
        """,
        entity=entity,
        type_tag=type_tag,
        notes=notes,
        number=number,
    )
