# AUTOGENERATED FROM 'src/queries/entity/CreateEntity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateEntityResult(NoPydanticValidation):
    id: uuid.UUID


async def CreateEntity(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
    email: str,
    type_tag: str,
    document_type: str,
    document: str,
    status: bool | None = None,
    sex: str | None = None,
    notes: str | None = None,
    relationship_status: str | None = None,
    birth: datetime.date | None = None,
) -> CreateEntityResult:
    return await executor.query_single(
        """\
        insert Entity {
            name:= <str>$name,
            email:= <str>$email,
            type_tag:= <str>$type_tag,
            document_type:= <str>$document_type,
            document:= <str>$document,
            status:= <optional bool>$status,
            sex:= <optional str>$sex,
            notes:=<optional json>$notes,
            relationship_status:= <optional str>$relationship_status,
            birth:= <optional cal::local_date>$birth,
        }\
        """,
        name=name,
        email=email,
        type_tag=type_tag,
        document_type=document_type,
        document=document,
        status=status,
        sex=sex,
        notes=notes,
        relationship_status=relationship_status,
        birth=birth,
    )
