# AUTOGENERATED FROM 'src/queries/entity/DeleteEntity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations

import dataclasses
import uuid

import gel


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = list
        return []


@dataclasses.dataclass
class DeleteEntityResult(NoPydanticValidation):
    id: uuid.UUID


async def DeleteEntity(
    executor: gel.AsyncIOExecutor,
    *,
    entity: uuid.UUID,
) -> DeleteEntityResult | None:
    return await executor.query_single(
        """\
        delete Entity filter .id = <uuid>$entity\
        """,
        entity=entity,
    )
