# AUTOGENERATED FROM 'src/queries/entity/UpdateEntity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateEntityResult(NoPydanticValidation):
    id: uuid.UUID


async def UpdateEntity(
    executor: gel.AsyncIOExecutor,
    *,
    email: str | None = None,
    type: str | None = None,
    id_type: str | None = None,
    status: bool | None = None,
    govt_id: str | None = None,
    name: str | None = None,
    sex: str | None = None,
    relationship_status: str | None = None,
    details: str | None = None,
    birth: datetime.date | None = None,
    entity: uuid.UUID,
) -> UpdateEntityResult | None:
    return await executor.query_single(
        """\
        update Entity filter .id = <uuid>$entity set {
            email:= <optional str>$email ?? .email,
            type:= <optional str>$type ?? .type,
            id_type:= <optional str>$id_type ?? .id_type,
            status:= <optional bool>$status ?? .status,
            govt_id:= <optional str>$govt_id ?? .govt_id,
            name:= <optional str>$name ?? .name,
            sex:= <optional str>$sex ?? .sex,
            relationship_status:= <optional str>$relationship_status ?? .relationship_status,
            details:= <optional json>$details ?? .details,
            birth:= <optional cal::local_date>$birth ?? .birth
        }\
        """,
        email=email,
        type=type,
        id_type=id_type,
        status=status,
        govt_id=govt_id,
        name=name,
        sex=sex,
        relationship_status=relationship_status,
        details=details,
        birth=birth,
        entity=entity,
    )
