# AUTOGENERATED FROM 'src/queries/entity/UpdateContact.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateContactResult(NoPydanticValidation):
    id: uuid.UUID


async def UpdateContact(
    executor: gel.AsyncIOExecutor,
    *,
    number: str | None = None,
    name: str | None = None,
    details: str | None = None,
    email: str | None = None,
    contact: uuid.UUID,
) -> UpdateContactResult | None:
    return await executor.query_single(
        """\
        update Contact filter .id = <uuid>$contact set{
            number:= <optional json>$number ?? .number,
            name:= <optional str>$name ?? .name,
            details:= <optional json>$details ?? .details,
            email:= <optional str>$email ?? .email
        }\
        """,
        number=number,
        name=name,
        details=details,
        email=email,
        contact=contact,
    )
