# AUTOGENERATED FROM 'src/queries/entity/UpdateEntity.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateEntityResult(NoPydanticValidation):
    id: uuid.UUID


async def UpdateEntity(
    executor: gel.AsyncIOExecutor,
    *,
    email: str | None = None,
    entity: uuid.UUID,
    type: str | None = None,
    id_type: str | None = None,
    status: bool | None = None,
    govt_id: str | None = None,
    name: str | None = None,
    sex: str | None = None,
    relationship_status: str | None = None,
    notes: str | None = None,
    birth: datetime.date | None = None,
) -> UpdateEntityResult | None:
    return await executor.query_single(
        """\
        with raw_email:= <optional str>$email,
        str_email:=(raw_email if exists raw_email else <str>{}),
        old_entity:=(select Entity filter .id = <uuid>$entity)
        update old_entity set {
            email:= str_email ?? .email,
            type:= <optional str>$type ?? old_entity.type,
            id_type:= <optional str>$id_type ?? old_entity.id_type,
            status:= <optional bool>$status ?? old_entity.status,
            govt_id:= <optional str>$govt_id ?? old_entity.govt_id,
            name:= <optional str>$name ?? old_entity.name,
            sex:= <optional str>$sex ?? old_entity.sex,
            relationship_status:= <optional str>$relationship_status ?? old_entity.relationship_status,
            notes:=<optional json>$notes ?? .notes,
            birth:= <optional cal::local_date>$birth ?? old_entity.birth
        }\
        """,
        email=email,
        entity=entity,
        type=type,
        id_type=id_type,
        status=status,
        govt_id=govt_id,
        name=name,
        sex=sex,
        relationship_status=relationship_status,
        notes=notes,
        birth=birth,
    )
